# Generated by Django 5.0.14 on 2025-07-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(max_length=100, unique=True)),
                ('routing_option', models.CharField(choices=[('Head of Office', 'Head of Office'), ('Deputy', 'Deputy'), ('Administrative Officer', 'Administrative Officer'), ('Examiner', 'Examiner')], max_length=50)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nature'],
            },
        ),
    ]
