# Generated by Django 5.0.14 on 2025-07-03 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointment_schedule', '0001_initial'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='admin_officer',
            field=models.ForeignKey(blank=True, limit_choices_to={'position': 'Administrative Officer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_appointments', to='personnel.personnel'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deputy',
            field=models.ForeignKey(blank=True, limit_choices_to={'position': 'Deputy'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deputy_appointments', to='personnel.personnel'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='examiner',
            field=models.ForeignKey(blank=True, limit_choices_to={'position': 'Examiner'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='examiner_appointments', to='personnel.personnel'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='head_of_office',
            field=models.ForeignKey(limit_choices_to={'position': 'Head of Office'}, on_delete=django.db.models.deletion.CASCADE, related_name='head_appointments', to='personnel.personnel'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('date', 'time_slot')},
        ),
    ]
