# Generated by Django 5.1.7 on 2025-07-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='sex',
            field=models.CharField(choices=[('Male', 'male'), ('Female', 'female')], default='Male', max_length=10),
        ),
    ]
